### ISSUE TITLE
SqliteHelper连接字符串bug

### ISSUE THREAD

**Issue by fettdrac** [crazywolfcode/SqlDaoDemo#1]
SqlDao.SQLiteHelper 类构造函数中，对于connstr的处理有问题
详细如下：
` public SQLiteHelper(string connstr)
        {
            if (string.IsNullOrEmpty(connstr))
            {
                throw new Exception("连接的字符串不正确。");//这里是不是改成”为空“更明确些？
            }
            else
            {
                //【BUG HERE】这里有问题，如果传入connstr=“data source=[dbPath]”的话，
//connstr会变成"DataSource=data source=[dbPath]"显然连接失败，建议直接把这段删了，透传，
//或者写个参数注释说只需要传入数据库文件路径即可
                if (!connstr.StartsWith("DataSource="))
                    connstr = "DataSource=" + connstr;
                connectionString = connstr;
            }
        }
`
如果不看源码，看错误就是：无法用给定字符串连接，一脸懵逼（滑稽）~

**Comment by crazywolfcode** [comment]
非常感谢您的指出，我会尽快处理



---原始邮件---
发件人: "fettdrac"<notifications@github.com&gt;
发送时间: 2020年1月16日(周四) 晚上10:49
收件人: "crazywolfcode/SqlDaoDemo"<SqlDaoDemo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [crazywolfcode/SqlDaoDemo] SqliteHelper连接字符串bug (#1)



SqlDao.SQLiteHelper 类构造函数中，对于connstr的处理有问题
 详细如下：
 public SQLiteHelper(string connstr) { if (string.IsNullOrEmpty(connstr)) { throw new Exception("连接的字符串不正确。");//这里是不是改成”为空“更明确些？ } else { //【BUG HERE】这里有问题，如果传入connstr=“data source=[dbPath]”的话， //connstr会变成"DataSource=data source=[dbPath]"显然连接失败，建议直接把这段删了，透传， //或者写个参数注释说只需要传入数据库文件路径即可 if (!connstr.StartsWith("DataSource=")) connstr = "DataSource=" + connstr; connectionString = connstr; } }
 如果不看源码，看错误就是：无法用给定字符串连接，一脸懵逼（滑稽）~
